# Generated by Django 4.0.4 on 2022-05-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_discription_alter_cart_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
