# Generated by Django 4.0.4 on 2022-06-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('banglore', 'banglore'), ('kochi', 'kochi'), ('hydrabad', 'hydrabad'), ('pune', 'pune')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='locality',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('KERALA', 'KERALA'), ('KARNATAKA', 'KARNATAKA'), ('ANDRA PRADESH', 'ANDRA PRADESH'), ('MAHARASHTA', 'MAHARASTRA')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
