# Generated by Django 3.2.13 on 2022-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customer_city_alter_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
