# Generated by Django 3.2.13 on 2022-06-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220606_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('PACKED', 'PACKED'), ('DELIVERED', 'DELIVERED'), ('CANCEL', 'CANCEL')], default='pending', max_length=50),
        ),
    ]
